#!/usr/bin/env bash

# start picom
picom --backend=glx --config ~/.config/picom/picom.conf &

bspc monitor DP-0 -d I II III IV V
bspc monitor DVI-D-0 -d VI VII VIII IX X

bspc rule -a Chromium-browser     desktop='^3'	follow=on
bspc rule -a librewolf            desktop='^3'	follow=on
bspc rule -a discord              desktop='^6'	follow=off
bspc rule -a Thunar 		          desktop='^7'	follow=on
bspc rule -a Lxappearance	        desktop='^10'	follow=off
bspc rule -a xst  			          desktop='^1'	follow=on
bspc rule -a Bitwarden 		        desktop='^8'	follow=on
bspc rule -a Lutris			          desktop='^4'	follow=on
bspc rule -a Postman		          desktop='^9'	follow=on
bspc rule -a Notepadqq		        desktop='^2' 	follow=on
bspc rule -a .gimp-2.10-wrapped_	desktop='^5'	follow=on
bspc rule -a BleachBit 		        desktop='^10'	follow=on
bspc rule -a gnome-calculator     desktop='^9'	follow=on
bspc rule -a Clementine		        desktop='^5'	follow=on
bspc rule -a haruna			          desktop='^5'	follow=on
bspc rule -a easyeffects	        desktop='^10' follow=on
bspc rule -a GParted		          desktop='^10'	follow=on
bspc rule -a kdenlive		          desktop='^5'	follow=on
bspc rule -a obs			            desktop='^5'	follow=on
bspc rule -a DesktopEditors	      desktop='^9'	follow=on
bspc rule -a Pavucontrol	        desktop='^10'	follow=on
bspc rule -a Nvidia-settings      desktop='^10'	follow=on
bspc rule -a Ristretto		        desktop='^5'	follow=on
bspc rule -a steam			          desktop='^4'	follow=on
bspc rule -a Virt-manager	        desktop='^5'	follow=on
bspc rule -a zoom			            desktop='^9'	follow=on
bspc rule -a qBittorrent	        desktop='^8' 	follow=on
bspc rule -a NeoVim 		          desktop='^2' 	follow=on # Open the NeoVim terminal window done by keybinds super + v on the second desktop
bspc rule -a Sonixd 		          desktop='^5' 	follow=on
bspc rule -a qutebrowser          desktop='^3'  follow=on
bspc rule -a ark                  desktop='^7'  follow=on
bspc rule -a Audacity             desktop='^5'  follow=on
bspc rule -a Ghb                  desktop='^5'  follow=on # ghb is hand brake
bspc rule -a mpv                  desktop='^5'  follow=on
bspc rule -a GOverlay             desktop='^4'  follow=on
bspc rule -a Inkscape             desktop='^5'  follow=on
bspc rule -a krita                desktop='^5'  follow=on
bspc rule -a easytag              desktop='^5'  follow=on
bspc rule -a Ardour               desktop='^10' follow=off
bspc rule -a bottles              desktop='^4'  follow=on
bspc rule -a Gnome-pomodoro       desktop='^10' follow=off

# Set resolution
xrandr --output DVI-D-0 --mode 1920x1080 --rate 144
xrandr --output DP-0 --mode 2560x1440 --rate 165
xrandr --output DP-0 --primary --left-of DVI-D-0

# Auto-Start
bspc desktop -f ^1
lxpolkit & # prompt to enter sudo password daemon
flameshot &

for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file" &
done

# run this last so it doesn't interupt other stuff.
lxappearance & # Fix cursor not showing on desktop (background)
sleep 3
pkill lxappearance # Fix cursor not showing on desktop (background)
