#!/usr/bin/env bash

# start picom
picom --backend=glx --config ~/.config/picom/picom.conf &

# Set resolution
xrandr --output DP-0 --mode 3840x2160 --rate 240 --primary
xrandr --output HDMI-0 --mode 2560x1440 --rate 144
xrandr --output HDMI-1 --mode 1920x1080 --rate 60
xrandr --output HDMI-1 --left-of DP-0
xrandr --output HDMI-0 --right-of DP-0

# Refresh wallpaper
feh --bg-fill --no-fehbg $XDG_DATA_HOME/wallpaper

# Configure workspaces
bspc monitor DP-0 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX
bspc monitor HDMI-1 -d X

# Set the order of the workspaces
bspc wm --reorder-monitors DP-0 HDMI-0 HDMI-1

# Set app rules
bspc rule -a Chromium-browser     desktop='^3'	follow=on
bspc rule -a librewolf            desktop='^3'	follow=on
bspc rule -a zen				  desktop='^3'	follow=on
bspc rule -a zen-beta		  		  desktop='^3'	follow=on
bspc rule -a discord              desktop='^6'	follow=off
bspc rule -a slack		  desktop='^6'	follow=off
bspc rule -a Thunar 		          desktop='^7'	follow=on
bspc rule -a Lxappearance	        desktop='^10'	follow=off
bspc rule -a xst  			          desktop='^1'	follow=on
bspc rule -a Alacritty  	          desktop='^1'	follow=on
bspc rule -a Bitwarden 		        desktop='^8'	follow=on
bspc rule -a Lutris			          desktop='^4'	follow=on
bspc rule -a Postman		          desktop='^9'	follow=on
bspc rule -a kate			 desktop='^2' 	follow=on
bspc rule -a .gimp-2.10-wrapped_	desktop='^5'	follow=on
bspc rule -a BleachBit 		        desktop='^10'	follow=on
bspc rule -a gnome-calculator     desktop='^9'	follow=on
bspc rule -a Clementine		        desktop='^5'	follow=on
bspc rule -a haruna			          desktop='^5'	follow=on
bspc rule -a easyeffects	        desktop='^10' follow=on
bspc rule -a GParted		          desktop='^10'	follow=on
bspc rule -a kdenlive		          desktop='^5'	follow=on
bspc rule -a obs			            desktop='^5'	follow=on
bspc rule -a DesktopEditors	      desktop='^9'	follow=on
bspc rule -a Pavucontrol	        desktop='^10'	follow=on
bspc rule -a Nvidia-settings      desktop='^10'	follow=on
bspc rule -a Ristretto		        desktop='^5'	follow=on
bspc rule -a steam			          desktop='^4'	follow=on
bspc rule -a Virt-manager	        desktop='^5'	follow=on
bspc rule -a zoom			            desktop='^9'	follow=on
bspc rule -a qBittorrent	        desktop='^8' 	follow=on
bspc rule -a NeoVim 		          desktop='^2' 	follow=on # Open the NeoVim terminal window done by keybinds super + v on the second desktop
bspc rule -a Sonixd 		          desktop='^5' 	follow=on
bspc rule -a qutebrowser          desktop='^3'  follow=on
bspc rule -a ark                  desktop='^7'  follow=on
bspc rule -a Audacity             desktop='^5'  follow=on
bspc rule -a Ghb                  desktop='^5'  follow=on # ghb is hand brake
bspc rule -a mpv                  desktop='^5'  follow=on
bspc rule -a GOverlay             desktop='^4'  follow=on
bspc rule -a Inkscape             desktop='^5'  follow=on
bspc rule -a krita                desktop='^5'  follow=on
bspc rule -a easytag              desktop='^5'  follow=on
bspc rule -a Ardour               desktop='^10' follow=off
bspc rule -a bottles              desktop='^4'  follow=on
bspc rule -a Gnome-pomodoro       desktop='^10' follow=off
bspc rule -a Blanket 		          desktop='^5' 	follow=off
bspc rule -a bruno                desktop='^4'  follow=on
bspc rule -a tidal-hifi           desktop='^5'  follow=on

# Auto-Start
bspc desktop -f ^1
lxpolkit & # prompt to enter sudo password daemon
flameshot &
easyeffects --gapplication-service & # easy effects for the eq for my headset
tmux new-session -d -s main & # for fast attach to tmux session
tmux new-session -d -s code & # for fast attach to tmux session
protonmail-bridge --noninteractive & # for email

for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file" &
done

# run this last so it doesn't interupt other stuff.
lxappearance & # Fix cursor not showing on desktop (background)
sleep 3
pkill lxappearance # Fix cursor not showing on desktop (background)

# Set mouse speed to match 1440p
xinput set-prop "Logitech G502 X" "libinput Accel Profile Enabled" 0 1
xinput set-prop "Logitech G502 X" "libinput Accel Speed" 0.5

# Start subscriber to reorder monitors on monitor power cycles
bspc subscribe monitor | while read -r _; do
    bspc wm --reorder-monitors DP-0 HDMI-0 HDMI-1
done &
