#!/usr/bin/env sh

bspc config border_width            1
bspc config window_gap              8
bspc config top_monocle_padding     0
bspc config right_monocle_padding   0
bspc config left_monocle_padding    0
bspc config bottom_monocle_padding  0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color   "#5d80ab"
bspc config normal_border_color    "#374151"
bspc config active_border_color	   "#374151"
bspc config presel_feedback_color  "#3b82f6"
